nine_twentytwo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

from verification.views import CaseListView, CaseDetailView, CaseUserListView, UploadView, MetaphaseListView, \
    MetaphaseDetailView


def redirect_root(request):
    return redirect('index')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', redirect_root),
    path('index/', CaseListView.as_view(), name='index'),
    path('mycases/', CaseUserListView.as_view(), name='my-cases'),
    path('case/<str:pk>', CaseDetailView.as_view(), name='case-detail'),
    path('upload/', UploadView.as_view()),
    path('label/', MetaphaseListView.as_view(), name='label'),
    path('label/<str:pk>', MetaphaseDetailView.as_view(), name='retrain'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

verification/models.py
import sys
from io import BytesIO

from django.contrib.auth.models import User
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
# Create your models here.
from django.db.models import Q
from django.utils.deconstruct import deconstructible

from verification.detection import nine_22


def to_imagefield(img):
    img_io = BytesIO()
    img.save(img_io, 'JPEG')
    ch_img = InMemoryUploadedFile(img_io, 'ImageField', str(img), 'image/jpeg', sys.getsizeof(img_io), None)
    return ch_img


class Case(models.Model):
    id = models.CharField(primary_key=True, verbose_name="Case ID", max_length=20)
    owner = models.ForeignKey(User, verbose_name="Physician", related_name='own', on_delete=models.SET_NULL, null=True)
    diff_diagnosis = models.CharField(max_length=100, verbose_name="Differential Diagnosis", null=True, blank=True)
    result = models.BooleanField(null=True, blank=True)
    upload_user = models.ForeignKey(User, related_name='upload', on_delete=models.SET_NULL, null=True)
    upload_time = models.DateTimeField(auto_now_add=True)
    modify_user = models.ForeignKey(User, related_name='modify', on_delete=models.SET_NULL, null=True)
    modify_time = models.DateTimeField(auto_now_add=True)
    confirm_user = models.ForeignKey(User, related_name='confirm', on_delete=models.SET_NULL, null=True, blank=True)
    confirm_time = models.DateTimeField(null=True, blank=True)
    confirm_status = models.BooleanField(null=True, blank=True)
    reject_message = models.CharField(max_length=200, null=True, blank=True)
    recheck_message = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        ordering = ('id', 'upload_time',)

    def __str__(self):
        return self.id

    @property
    def count_der(self):
        meta_result = []
        for meta_img in self.get_metaphases:
            meta_result.append(meta_img.result == 1)
        return sum(result for result in meta_result)

    @property
    def get_metaphases(self):
        return MetaphaseImage.objects.filter(case=self).order_by('id')

    @property
    def get_new_metaphases(self):
        return MetaphaseImage.objects.filter(
            Q(case=self) & Q(result=None)
        ).order_by('id')

    def predict(self):
        meta_filenames = []
        for meta_img in self.get_new_metaphases:
            meta_filenames.append(meta_img.original_image)

        print('detection started...')
        prediction = nine_22(meta_filenames)
        print('...interpreting...')

        for i, meta_img in enumerate(self.get_new_metaphases, 1):
            meta_img.result_image = to_imagefield(prediction[i]['framed'])
            meta_img.save(flag=False)

            for j in range(len(prediction[i]['img_9'])):
                chromosome = ChromosomeImage(metaphase=meta_img,
                                             type=9,
                                             prediction=prediction[i]['pred_9'][j],
                                             image=to_imagefield(prediction[i]['img_9'][j]),
                                             prob=prediction[i]['prob_9'][j] * 100)
                chromosome.save()

            for j in range(len(prediction[i]['img_22'])):
                chromosome = ChromosomeImage(metaphase=meta_img,
                                             type=22,
                                             prediction=prediction[i]['pred_22'][j],
                                             image=to_imagefield(prediction[i]['img_22'][j]),
                                             prob=prediction[i]['prob_22'][j] * 100)
                chromosome.save()

            # save all cropped chromosomes images to show in labeling page
            # for j in range(len(prediction[i]['ch'])):
            #     ch_img = array_to_img(prediction[i]['ch'][j])
            #     chromosome = ChromosomeImage(metaphase=meta_img,
            #                                  type=0,
            #                                  image=to_imagefield(ch_img))
            #     chromosome.save()

            if prediction[i]['result'] == -1:
                meta_img.result = None
            else:
                meta_img.result = prediction[i]['result']

            meta_img.save(flag=False)

        meta_result = []
        for meta_img in self.get_metaphases:
            meta_result.append(meta_img.result)

        print('...detection finished')
        print('---------------------------')
        print("ph detection result:", meta_result)

        if 1 in meta_result:
            return True
        elif 0 in meta_result:
            return False
        else:
            return None

    def save(self, flag=False, *args, **kwargs):
        if self.get_new_metaphases is not None and flag:
            self.result = self.predict()
            self.save(flag=False, *args, **kwargs)
        return super(Case, self).save(*args, **kwargs)


@deconstructible
class ImagePath(object):

    def __init__(self, img_name):
        self.img_name = img_name

    def __call__(self, instance, filename):
        if isinstance(instance, MetaphaseImage):
            return '/'.join([instance.case.id, instance.id, self.img_name + ".jpg"])
        else:
            return '/'.join([instance.metaphase.case.id, instance.metaphase.id, instance.name + ".jpg"])


def set_images_path(image_name):
    return ImagePath(image_name)


class MetaphaseImage(models.Model):
    id = models.CharField(primary_key=True, max_length=30, default='none')
    original_image = models.ImageField(upload_to=set_images_path("original"))
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    upload_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    result = models.BooleanField(null=True, blank=True)
    result_image = models.ImageField(upload_to=set_images_path("result"), null=True, blank=True)

    class Meta:
        ordering = ('case', 'id',)

    def save(self, flag=True, *args, **kwargs):
        if flag:
            name = "%02d" % (MetaphaseImage.objects.filter(case=self.case).count() + 1)
            self.id = self.case.id + "_" + name
            self.save(flag=False, *args, **kwargs)
        return super(MetaphaseImage, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.id)

    @property
    def get_result(self):
        if self.result == 1:
            return 'found'
        elif self.result == 0:
            return 'not found'
        else:
            return 'cannot detect'

    @property
    def get_chromosome9(self):
        return ChromosomeImage.objects.filter(
            Q(metaphase=self) & Q(type=9)
        ).order_by('name')

    @property
    def get_chromosome22(self):
        return ChromosomeImage.objects.filter(
            Q(metaphase=self) & Q(type=22)
        ).order_by('name')


class ChromosomeImage(models.Model):
    id = models.CharField(primary_key=True, max_length=30, default='none')
    name = models.CharField(max_length=5, default='none')
    metaphase = models.ForeignKey(MetaphaseImage, on_delete=models.CASCADE)
    type = models.IntegerField(choices=((9, 'Chromosome 9'), (22, 'Chromosome 22'), (0, 'Chromosome')))
    prediction = models.BooleanField(null=True, blank=True)
    image = models.ImageField(upload_to=set_images_path("."), null=True, blank=True)
    prob = models.IntegerField(null=True, blank=True)

    def save(self, flag=True, *args, **kwargs):
        if flag:
            number = ChromosomeImage.objects.filter(
                Q(metaphase=self.metaphase) & Q(type=self.type)
            ).count()
            if self.type == 0:
                self.name = 'ch' + str(number+1)
            else:
                self.name = str(self.type) + chr(65 + number)
            self.id = self.metaphase.id + "_" + self.name
            self.save(flag=False, *args, **kwargs)
        return super(ChromosomeImage, self).save(*args, **kwargs)

    @property
    def get_prediction(self):
        if self.prediction == 0:
            return "NM"
        elif self.prediction == 1 and self.type == 9:
            return "DER"
        elif self.prediction == 1 and self.type == 22:
            return "PH"
        return "None"

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <style type="text/css">
        * {
            margin: 0;
            padding: 0;
        }

        <!-- metaphases image -->
        .carousel .carousel-indicators li {
          background-color: #fff;
          background-color: rgba(70, 70, 70, 0.25);
        }

        .carousel .carousel-indicators .active {
          background-color: #444;
        }

        <!-- upload form -->
        .form-group>label{
            font-weight: bold;
        }


        .fab-label {
            position: fixed;
            bottom: 50px;
            right: 110px;
            display: table;
            visibility: hidden;
        }

        .fab-text {
            color: #FFF;
            background: rgba(51,51,51,0.5);
            display: table-cell;
            vertical-align: middle;
            padding: 7px;
            border-radius: 3px;
        }

        .fab-icon-holder {
            position: fixed;
            width: 60px;
            height: 60px;
            bottom: 40px;
            right: 40px;
            background-color: #D76C5E;
            border-radius: 50px;
            text-align: center;
            box-shadow: 2px 2px 3px #999;

            opacity: 1;
        }

        .fab-icon {
            font-size: 24px;
            margin-top: 18px;
        }

        a.fab-icon-holder + div.fab-label {
          visibility: hidden;
          opacity: 0;
          transition: visibility 0s, opacity 0.5s ease;
        }

        a.fab-icon-holder:hover + div.fab-label {
          visibility: visible;
          opacity: 1;
        }

        a.fab-icon-holder:hover {
            opacity: 0.85;
        }
    </style>

    <!--  CSS  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!--  Icons  -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!--  Material Design  -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <!--  JS, Popper.js, and jQuery  -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <title>{% block title %}Authentication{% endblock %}</title>
</head>
<body style="background-color: #F0F0F2;">

    {% block navbar %}
    <nav class="navbar fixed-top navbar-expand-lg navbar-light py-1" style="background-color: #2FBECD;">
    {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'index' %}">9-22</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar" aria-controls="myNavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="myNavbar">
            <ul class="navbar-nav mt-2 mt-lg-0 ">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}"><i class="fas fa-home"></i> Home</a>
                </li>
                {% if perms.verification.add_metaphaseimage %}
                <li class="nav-item">
                    <a class="nav-link" href="/upload"><i class="fas fa-folder-plus"></i> Upload</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0 ">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user"></i> Hello, {{ user.get_username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if perms.verification.view_case %}
                        <a class="dropdown-item" href="/mycases"><i class="fas fa-clipboard-list"></i> My cases</a>
                        {% if perms.verification.add_metaphaseimage %}
                        <a class="dropdown-item" href="/label"><i class="fas fa-tag"></i> Label</a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'logout' %}?next={{ request.path }}"><i
                                class="fas fa-sign-out-alt"></i> Logout</a>
                    </div>
                </li>
            </ul>
        </div>
        {% else %}
        <a class="navbar-brand text-uppercase" href="/allcases">9-22</a>
    {% endif %}
    </nav>
    {% endblock %}

<div id="content" class="main pt-5">
    {% block content %}{% endblock %}
</div>
</body>
</html>